//! `cargo fips init` — scaffold a `fips.toml` by detecting the backend in the
//! resolved dependency graph.
//!
//! Runs `cargo metadata`, detects a validated backend, and fills in the module,
//! certificate, validated version, and the certificate's tested operating
//! environments (from the built-in registry), plus the host target. When no
//! backend is detected it writes a template with `TODO` placeholders. It refuses
//! to overwrite an existing `fips.toml` without `--force`.

use cargo_fips_registry::Registry;

use crate::backend;
use crate::cli::{FipsCli, InitArgs};
use crate::environment::host_triple;
use crate::exit::Exit;
use crate::metadata::Graph;

pub fn run(cli: &FipsCli, args: &InitArgs) -> Exit {
    let manifest_dir = cli.manifest_dir();
    let output = args
        .output
        .clone()
        .unwrap_or_else(|| manifest_dir.join("fips.toml"));

    if output.exists() && !args.force {
        eprintln!(
            "error: {} already exists (use --force to overwrite)",
            output.display()
        );
        return Exit::Usage;
    }

    let graph = match Graph::load(cli.manifest_path.as_deref(), None) {
        Ok(graph) => graph,
        Err(err) => {
            eprintln!("error: {err:#}");
            return Exit::Usage;
        }
    };

    let registry = Registry::builtin().ok();
    let host = host_triple();
    let backends = backend::detect_backends(&graph);

    let (content, summary) = match backends.first() {
        Some((be, detected)) => {
            let identity = be.module_identity(&graph);
            let cert = identity.certificates.first().cloned();
            let entry = cert
                .as_deref()
                .and_then(|c| registry.as_ref().and_then(|r| r.certificate(c)));

            let module = entry
                .map(|e| e.module.id.clone())
                .unwrap_or_else(|| identity.module_id.clone());
            let version = entry.and_then(|e| e.certificate.validated_versions.first().cloned());
            let tested: Vec<String> = entry
                .map(|e| {
                    e.binding
                        .tested_operating_environments
                        .iter()
                        .flat_map(|oe| oe.target_triples.clone())
                        .collect()
                })
                .unwrap_or_default();

            let content = render_fips_toml(
                detected.name,
                &module,
                cert.as_deref(),
                version.as_deref(),
                host.as_deref(),
                &tested,
            );
            let summary = match &cert {
                Some(c) => format!("detected backend `{}` (certificate #{c})", detected.name),
                None => format!(
                    "detected backend `{}` (no certificate pinned — fill it in)",
                    detected.name
                ),
            };
            (content, summary)
        }
        None => (
            render_template(host.as_deref()),
            "no validated backend detected — wrote a template with placeholders".to_string(),
        ),
    };

    if let Some(parent) = output.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    if let Err(err) = std::fs::write(&output, content) {
        eprintln!("error: writing {}: {err}", output.display());
        return Exit::Usage;
    }

    if cli.quiet {
        println!("{}", output.display());
        return Exit::Pass;
    }

    println!("cargo fips init");
    println!("  {summary}");
    if let Some(h) = &host {
        println!("  host target: {h}");
    }
    println!("  wrote {}", output.display());
    println!("  review the values, then run `cargo fips check`.");

    Exit::Pass
}

fn render_fips_toml(
    backend_name: &str,
    module: &str,
    cert: Option<&str>,
    version: Option<&str>,
    host: Option<&str>,
    tested: &[String],
) -> String {
    let cert = cert.unwrap_or("TODO");
    let version = version.unwrap_or("TODO");
    let host_oe = host.unwrap_or("x86_64-unknown-linux-gnu");

    let tested_comment = if tested.is_empty() {
        String::new()
    } else {
        let mut triples: Vec<&str> = tested.iter().map(String::as_str).collect();
        triples.sort_unstable();
        triples.dedup();
        format!(
            "\n# tested OEs for certificate #{cert}: {}",
            triples.join(", ")
        )
    };

    format!(
        r#"# Generated by `cargo fips init`. Review every value before relying on it (spec §7).

[target]
certificate = "{cert}"
module      = "{module}"
version     = "{version}"{tested_comment}
allowed_oes = ["{host_oe}"]
strictness  = "tested-only"          # tested-only | allow-vendor-affirmed

[policy]
forbid_competing_crypto = true
allowed_backends        = ["{backend_name}"]
deny_off_certificate_oe = true

[attest]
format     = "cyclonedx-cbom-1.6"
output     = "target/fips/attestation.cdx.json"
provenance = true
sign       = false

[registry]
source = "builtin"
"#
    )
}

fn render_template(host: Option<&str>) -> String {
    let host_oe = host.unwrap_or("x86_64-unknown-linux-gnu");
    format!(
        r#"# Generated by `cargo fips init`.
# No validated FIPS backend was detected in the dependency graph, so this is a
# template — fill in the TODOs. See the spec, §7. Known backends/certificates
# include: aws-lc-rs -> #4816, wolfCrypt -> #4718/#5041, OpenSSL provider -> #4857.

[target]
certificate = "TODO"   # e.g. "4816"
module      = "TODO"   # e.g. "aws-lc-fips"
version     = "TODO"   # e.g. "AWS-LC-FIPS-2.0"
allowed_oes = ["{host_oe}"]
strictness  = "tested-only"

[policy]
forbid_competing_crypto = true
allowed_backends        = []   # e.g. ["aws-lc-rs"]
deny_off_certificate_oe = true

[attest]
format     = "cyclonedx-cbom-1.6"
output     = "target/fips/attestation.cdx.json"
provenance = true
sign       = false

[registry]
source = "builtin"
"#
    )
}
